### ISSUE TITLE
createCertificate is failed with config option?

### ISSUE THREAD

**Issue by ghost** [Dexus/pem#184]
I set options.config with openssl.cfg content, but it always runs in error. 
How I can set a global openssl.cfg file?
```JS
pem.config({
        pathOpenSSL: opensslPath
    });

 let options = {
        keyBitsize: 2048,
        days: 3650,
        hash: 'sha256',
        selfSigned: true,
        config: fs.readFileSync(opensslConfPath)

    };
    pem.createCertificate(options, function (err, keys) {
        console.log(err);
        console.log(keys);
        if (err) {
            vscode.window.showErrorMessage('OPENSSL_CONF env is not set, certificate.pem is generated failed!');
            throw err;
        }
        if (keys) {}
```

```
Error: Invalid openssl exit code: 1
signHelper.js:31
% openssl req -new -sha256 -subj /CN=localhost -key C:\Users\B00299~1\AppData\Local\Temp\a53cd6a0a1a35eeb17ce463d40abe146fe215974
Can't open C:\Program Files\Common Files\SSL/openssl.cnf for reading, No such file or directory
33144:error:02001003:system library:fopen:No such process:crypto\bio\bss_file.c:74:fopen('C:\Program Files\Common Files\SSL/openssl.cnf','r')
33144:error:2006D080:BIO routines:BIO_new_file:no such file:crypto\bio\bss_file.c:81:
unable to find 'distinguished_name' in config
problems making Certificate Request
33144:error:0E06D06A:configuration file routines:NCONF_get_string:no conf or environment variable:crypto\conf\conf_lib.c:272:
	at done (e:\projects-code\IDE\extensions\deveco-ux-menu\node_modules\pem\lib\openssl.js:159:27)
	at ChildProcess.<anonymous> (e:\projects-code\IDE\extensions\deveco-ux-menu\node_modules\pem\lib\openssl.js:176:7)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at maybeClose (internal/child_process.js:899:16)
	at Process.__dirname.ChildProcess._handle.onexit (internal/child_process.js:226:5)
undefined
```

**Comment by Dexus** [comment]
Please use the correct Path to your openssl.cnf 

`Can't open C:\Program Files\Common Files\SSL/openssl.cnf for reading, No such file or directory`  looks like you don't set the path correct because on windows you have to use `\` not  `/`
