### ISSUE TITLE
npm install pem don't work

### ISSUE THREAD

**Issue by Attila972** [Dexus/pem#187]
```
$npm install pem
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "md5@^2.2.1": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hh/.npm/_logs/2018-03-28T15_56_39_964Z-debug.log
```

**Comment by Dexus** [comment]
Can you please give me some more informations? Node Version and NPM version?

and or please provide you npm debug log.
Thanks

**Comment by Attila972** [comment]
node@v6.10.0 / npm@5.8.0

npm debug log give : 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install', 'pem' ]
2 info using npm@5.8.0
3 info using node@v6.10.0
4 verbose npm-session 2be25d86fbd62173
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 http://.../npm/pem 255ms
8 silly pacote version manifest for pem@1.12.5 fetched in 290ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule pem@1.12.5 checking installable status
14 silly removeObsoleteDep removing pem@1.12.5 from the tree as its been replaced by a newer version or is no longer required
15 silly removeObsoleteDep removing which@1.3.0 from the tree as its been replaced by a newer version or is no longer required
16 silly removeObsoleteDep removing isexe@2.0.0 from the tree as its been replaced by a newer version or is no longer required
17 http fetch GET 200 http://.../npm/which 169ms
18 silly pacote range manifest for which@^1.2.4 fetched in 172ms
19 silly resolveWithNewModule which@1.3.0 checking installable status
20 http fetch GET 200 http://.../npm/md5 282ms
21 silly pacote range manifest for md5@^2.2.1 fetched in 286ms
22 silly resolveWithNewModule MD5@2.2.1 checking installable status
23 verbose stack Error: Invalid tag name "md5@^2.2.1": Tags may not have any characters that encodeURIComponent encodes.
23 verbose stack     at invalidTagName (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:85:15)
23 verbose stack     at fromRegistry (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:272:13)
23 verbose stack     at Function.resolve (/usr/local/lib/node_modules/npm/node_modules/npm-package-arg/npa.js:75:12)
23 verbose stack     at doesChildVersionMatch (/usr/local/lib/node_modules/npm/lib/install/deps.js:69:25)
23 verbose stack     at isDep (/usr/local/lib/node_modules/npm/lib/install/deps.js:142:27)
23 verbose stack     at addRequiredDep (/usr/local/lib/node_modules/npm/lib/install/deps.js:154:13)
23 verbose stack     at addBundled (/usr/local/lib/node_modules/npm/lib/install/deps.js:659:7)
23 verbose stack     at addBundled (/usr/local/lib/node_modules/npm/lib/fetch-package-metadata.js:93:78)
23 verbose stack     at isInstallable (/usr/local/lib/node_modules/npm/lib/install/deps.js:637:5)
23 verbose stack     at checkPlatform (/usr/local/lib/node_modules/npm/node_modules/npm-install-checks/index.js:53:10)
23 verbose stack     at thenWarnEngineIssues (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:52:5)
23 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/iferr/index.js:13:50
23 verbose stack     at checkEngine (/usr/local/lib/node_modules/npm/node_modules/npm-install-checks/index.js:10:20)
23 verbose stack     at module.exports.isInstallable (/usr/local/lib/node_modules/npm/lib/install/validate-args.js:49:3)
23 verbose stack     at resolveWithNewModule (/usr/local/lib/node_modules/npm/lib/install/deps.js:635:10)
23 verbose stack     at /usr/local/lib/node_modules/npm/lib/install/deps.js:558:7
24 verbose cwd /Users/...
25 verbose Darwin 15.6.0
26 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pem"
27 verbose node v6.10.0
28 verbose npm  v5.8.0
29 error code EINVALIDTAGNAME
30 error Invalid tag name "md5@^2.2.1": Tags may not have any characters that encodeURIComponent encodes.
31 verbose exit [ 1, true ]

```


I've reverse npm to 3.10.10 (version come with node v6.10.0) then it's worked

```
$npm install pem
...
└─┬ pem@1.12.5 
  └── MD5@2.2.1  extraneous

```

**Comment by Dexus** [comment]
good to know, not yet updated npm to the last version without last node version. Never had this issue. So its maybe npm related and not with our package.

**Comment by Attila972** [comment]
Apparently npm fetch "MD5@2.2.1" (in capitalize instead of md5@2.2.1) maybe update your package.json with MD5@2.2.1 will solve it, also may be fix dependencies version in your package.json provide you more stability with large panel of node / npm version (I don't know if it's a good practice, but resolve dependencies with npm, it's some time a hell...).

However thank's for developping pem, it's the only complete openssl node wrapper I founded for my need!

**Comment by Dexus** [comment]
this will not work, because there is no capitalized MD5 package at npmjs.
I think its a bug at npm itself.
You're welcome.
