### ISSUE TITLE
can't create csr from private key

### ISSUE THREAD

**Issue by farouk404** [Dexus/pem#244]
var csrOptions = {
        clientKey: '/root/ca/intermediate/private/client.key.pem',
        clientKeyPassword: '123456',
        hash: 'sha256',
        country: 'US',
        state: 'California',
        locality: 'Mountain View',
        organization: 'Alice Ltd',
        organizationUnit: 'Alice Ltd Web Services',
        commonName: 'pass:client',
        csrConfigFile: '/root/ca/intermediate/openssl.cnf'
    }

    pem.createCSR( csrOptions , function(err, csr) {
        if (err) {
            throw err
        } else {
            console.log(csr.clientKey)
            console.log(csr.csr)
        }

    });

Error

    Error: Invalid openssl exit code: 1
    % openssl req -new -sha256 -config /root/ca/intermediate/openssl.cnf -key 
    /tmp/aba6774164257ab7be48ab400f1163bb063053a7 -passin 
    file:/tmp/791e456fe45b249961a9dd89f02b687642377a45
    unable to load Private Key
    139824679817664:error:0906D06C:PEM routines:PEM_read_bio:no start 
    line:../crypto/pem/pem_lib.c:691:Expecting: ANY PRIVATE KEY

    at done (/root/sslnode/node_modules/pem/lib/openssl.js:158:27)
    at ChildProcess.<anonymous> (/root/sslnode/node_modules/pem/lib/openssl.js:175:7)
    at ChildProcess.emit (events.js:188:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)

**Comment by farouk404** [comment]
After searching i found the error in

`clientKey: '/root/ca/intermediate/private/client.key.pem',`
this param took a string not a path

`clientKey: fs.readFileSync('/root/ca/intermediate/private/client.key.pem'),`
and no need to define openssl.cnf

`csrConfigFile: '/root/ca/intermediate/openssl.cnf'`
