### ISSUE TITLE
How to decrypt https server buffer?

### ISSUE THREAD

**Issue by gajus** [Dexus/pem#260]
I have created an internal HTTPS server using:

```js
const internalHttpsServer = https.createServer(
  {
    ca: sslCertificate.csr,
    cert: sslCertificate.certificate,
    key: sslCertificate.serviceKey
  },
  requestHandler
);

```

Now I am trying to intercept and print the communication between client and the https server:

```js
const serverSocket = net.connect({
  path
}, () => {
  requestSocket.write(
    'HTTP/' + httpVersion + ' 200 Connection established\r\n' +
    'proxy-agent: raygun\r\n' +
    '\r\n'
  );

  serverSocket.write(head);

  serverSocket
    .pipe(through((chunk, enc, callback) => {
      try {
        console.log('server socket ->', crypto.publicDecrypt(sslCertificate.serviceKey, chunk).toString('utf8'));
      } catch (error) {
        console.log('error', error);
      }

      callback(null, chunk);
    }))
    .pipe(requestSocket);

  requestSocket
    .pipe(serverSocket);
});

```

This is giving invalid padding error:

```
error Error: error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding
    at Object.publicDecrypt (internal/crypto/cipher.js:53:12)
    at DestroyableTransform.publicDecrypt [as _transform] (/Users/gajus/Documents/dev/applaudience/raygun/src/handlers/handleConnect.js:56:50)
    at DestroyableTransform.Transform._read (/Users/gajus/Documents/dev/applaudience/raygun/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/gajus/Documents/dev/applaudience/raygun/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/gajus/Documents/dev/applaudience/raygun/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/gajus/Documents/dev/applaudience/raygun/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/gajus/Documents/dev/applaudience/raygun/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:713:22)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12) {
  opensslErrorStack: [
    'error:04067072:rsa routines:rsa_ossl_public_decrypt:padding check failed'
  ],
  library: 'rsa routines',
  function: 'RSA_padding_check_PKCS1_type_1',
  reason: 'invalid padding',
  code: 'ERR_OSSL_RSA_INVALID_PADDING'
}
error Error: error:0406706C:rsa routines:rsa_ossl_public_decrypt:data greater than mod len
    at Object.publicDecrypt (internal/crypto/cipher.js:53:12)
    at DestroyableTransform.publicDecrypt [as _transform] (/Users/gajus/Documents/dev/applaudience/raygun/src/handlers/handleConnect.js:56:50)
    at DestroyableTransform.Transform._read (/Users/gajus/Documents/dev/applaudience/raygun/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/gajus/Documents/dev/applaudience/raygun/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/gajus/Documents/dev/applaudience/raygun/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/gajus/Documents/dev/applaudience/raygun/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/gajus/Documents/dev/applaudience/raygun/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at Socket.ondata (_stream_readable.js:713:22)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12) {
  library: 'rsa routines',
  function: 'rsa_ossl_public_decrypt',
  reason: 'data greater than mod len',
  code: 'ERR_OSSL_RSA_DATA_GREATER_THAN_MOD_LEN'
}

```

What is the right way to intercept and decrypt https server buffer?

Note: I am aware that I can just use the request handler of the https server. I am wanting to understand this to broaden my understanding of the protocol.

**Comment by gajus** [comment]
My understanding of CONNECT tunnel is as follows: client makes CONNECT request. This is where the HTTPS handshakes happen. If server responds 'HTTP/1.1 200 Connection Established', then clients knows it successfully negotiated keys and starts exchanging encrypted traffic.

My understanding is that `serverSocket.pipe(requestSocket); requestSocket.pipe(serverSocket);` is where all of this encrypted traffic (which should be just HTTP) is being exchanged and that if I have the original TLS key/ cert I should be able to intercept it and print it as plain text.

**Comment by Dexus** [comment]
This it’s not pem related so I can’t help you.

Regards, Josef
